export {default as HomePage} from './home/home_page'
export {default as AboutPage} from './about/about_page'
export {default as ProjectPage} from './projects/project_page'
export {default as Contact} from './contacts/contact_page'
export {default as OurTeam} from './team/team'