export {default as Carousel} from './carousel/carousel'
export {default as About} from './about/about'
export {default as OurService} from './serives/our_service'
export {default as CoreValues} from './core_values/core'
export {default as CEO} from './ceo/ceo'
export {default as OtherBusinss} from './other_business/business'
export {default as MoreBusiness} from './more_info/more_info'